/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAnswer.h
 *
 * 
 */

#ifndef OAIAnswer_H
#define OAIAnswer_H

#include <QJsonObject>

#include "OAIAnswer_answers_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAnswer : public OAIObject {
public:
    OAIAnswer();
    OAIAnswer(QString json);
    ~OAIAnswer() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getSessionId() const;
    void setSessionId(const QString &session_id);
    bool is_session_id_Set() const;
    bool is_session_id_Valid() const;

    QString getQuestionId() const;
    void setQuestionId(const QString &question_id);
    bool is_question_id_Set() const;
    bool is_question_id_Valid() const;

    QList<OAIAnswer_answers_inner> getAnswers() const;
    void setAnswers(const QList<OAIAnswer_answers_inner> &answers);
    bool is_answers_Set() const;
    bool is_answers_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString session_id;
    bool m_session_id_isSet;
    bool m_session_id_isValid;

    QString question_id;
    bool m_question_id_isSet;
    bool m_question_id_isValid;

    QList<OAIAnswer_answers_inner> answers;
    bool m_answers_isSet;
    bool m_answers_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAnswer)

#endif // OAIAnswer_H
