/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChallengeID.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIChallengeID::OAIChallengeID(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChallengeID::OAIChallengeID() {
    this->initializeModel();
}

OAIChallengeID::~OAIChallengeID() {}

void OAIChallengeID::initializeModel() {

    m_gid_isSet = false;
    m_gid_isValid = false;
}

void OAIChallengeID::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChallengeID::fromJsonObject(QJsonObject json) {

    m_gid_isValid = ::OpenAPI::fromJsonValue(gid, json[QString("gid")]);
    m_gid_isSet = !json[QString("gid")].isNull() && m_gid_isValid;
}

QString OAIChallengeID::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChallengeID::asJsonObject() const {
    QJsonObject obj;
    if (m_gid_isSet) {
        obj.insert(QString("gid"), ::OpenAPI::toJsonValue(gid));
    }
    return obj;
}

QString OAIChallengeID::getGid() const {
    return gid;
}
void OAIChallengeID::setGid(const QString &gid) {
    this->gid = gid;
    this->m_gid_isSet = true;
}

bool OAIChallengeID::is_gid_Set() const{
    return m_gid_isSet;
}

bool OAIChallengeID::is_gid_Valid() const{
    return m_gid_isValid;
}

bool OAIChallengeID::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_gid_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChallengeID::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_gid_isValid && true;
}

} // namespace OpenAPI
