/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChallenge.h
 *
 * 
 */

#ifndef OAIChallenge_H
#define OAIChallenge_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIChallenge : public OAIObject {
public:
    OAIChallenge();
    OAIChallenge(QString json);
    ~OAIChallenge() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getGid() const;
    void setGid(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    double getTotalQuestion() const;
    void setTotalQuestion(const double &total_question);
    bool is_total_questions_Set() const;
    bool is_total_questions_Valid() const;

    double getMaxTime() const;
    void setMaxTime(const double &max_time);
    bool is_max_time_Set() const;
    bool is_max_time_Valid() const;

    QString getTestType() const;
    void setTestType(const QString &test_type);
    bool is_test_type_Set() const;
    bool is_test_type_Valid() const;

    QString getSection() const;
    void setSection(const QString &section);
    bool is_section_Set() const;
    bool is_section_Valid() const;

    QList<QString> getSubsection() const;
    void setSubsection(const QList<QString> &subsection);
    bool is_subsection_Set() const;
    bool is_subsection_Valid() const;

    QString getAnnotation() const;
    void setAnnotation(const QString &annotation);
    bool is_annotation_Set() const;
    bool is_annotation_Valid() const;

    QList<QString> getQIds() const;
    void setQIds(const QList<QString> &q_ids);
    bool is_q_ids_Set() const;
    bool is_q_ids_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    double total_question;
    bool m_total_questions_isSet;
    bool m_total_questions_isValid;

    double max_time;
    bool m_max_time_isSet;
    bool m_max_time_isValid;

    QString test_type;
    bool m_test_type_isSet;
    bool m_test_type_isValid;

    QString section;
    bool m_section_isSet;
    bool m_section_isValid;

    QList<QString> subsection;
    bool m_subsection_isSet;
    bool m_subsection_isValid;

    QString annotation;
    bool m_annotation_isSet;
    bool m_annotation_isValid;

    QList<QString> q_ids;
    bool m_q_ids_isSet;
    bool m_q_ids_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIChallenge)

#endif // OAIChallenge_H
