/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPushAnswer_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPushAnswer_request::OAIPushAnswer_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPushAnswer_request::OAIPushAnswer_request() {
    this->initializeModel();
}

OAIPushAnswer_request::~OAIPushAnswer_request() {}

void OAIPushAnswer_request::initializeModel() {

    m_session_id_isSet = false;
    m_session_id_isValid = false;

    m_question_id_isSet = false;
    m_question_id_isValid = false;

    m_answers_isSet = false;
    m_answers_isValid = false;
}

void OAIPushAnswer_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPushAnswer_request::fromJsonObject(QJsonObject json) {

    m_session_id_isValid = ::OpenAPI::fromJsonValue(session_id, json[QString("session_id")]);
    m_session_id_isSet = !json[QString("session_id")].isNull() && m_session_id_isValid;

    m_question_id_isValid = ::OpenAPI::fromJsonValue(question_id, json[QString("question_id")]);
    m_question_id_isSet = !json[QString("question_id")].isNull() && m_question_id_isValid;

    m_answers_isValid = ::OpenAPI::fromJsonValue(answers, json[QString("answers")]);
    m_answers_isSet = !json[QString("answers")].isNull() && m_answers_isValid;
}

QString OAIPushAnswer_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPushAnswer_request::asJsonObject() const {
    QJsonObject obj;
    if (m_session_id_isSet) {
        obj.insert(QString("session_id"), ::OpenAPI::toJsonValue(session_id));
    }
    if (m_question_id_isSet) {
        obj.insert(QString("question_id"), ::OpenAPI::toJsonValue(question_id));
    }
    if (answers.size() > 0) {
        obj.insert(QString("answers"), ::OpenAPI::toJsonValue(answers));
    }
    return obj;
}

QString OAIPushAnswer_request::getSessionId() const {
    return session_id;
}
void OAIPushAnswer_request::setSessionId(const QString &session_id) {
    this->session_id = session_id;
    this->m_session_id_isSet = true;
}

bool OAIPushAnswer_request::is_session_id_Set() const{
    return m_session_id_isSet;
}

bool OAIPushAnswer_request::is_session_id_Valid() const{
    return m_session_id_isValid;
}

QString OAIPushAnswer_request::getQuestionId() const {
    return question_id;
}
void OAIPushAnswer_request::setQuestionId(const QString &question_id) {
    this->question_id = question_id;
    this->m_question_id_isSet = true;
}

bool OAIPushAnswer_request::is_question_id_Set() const{
    return m_question_id_isSet;
}

bool OAIPushAnswer_request::is_question_id_Valid() const{
    return m_question_id_isValid;
}

QList<OAIAnswer> OAIPushAnswer_request::getAnswers() const {
    return answers;
}
void OAIPushAnswer_request::setAnswers(const QList<OAIAnswer> &answers) {
    this->answers = answers;
    this->m_answers_isSet = true;
}

bool OAIPushAnswer_request::is_answers_Set() const{
    return m_answers_isSet;
}

bool OAIPushAnswer_request::is_answers_Valid() const{
    return m_answers_isValid;
}

bool OAIPushAnswer_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_session_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_question_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (answers.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPushAnswer_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
