/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISession_userInfo.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISession_userInfo::OAISession_userInfo(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISession_userInfo::OAISession_userInfo() {
    this->initializeModel();
}

OAISession_userInfo::~OAISession_userInfo() {}

void OAISession_userInfo::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_group_isSet = false;
    m_group_isValid = false;
}

void OAISession_userInfo::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISession_userInfo::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_group_isValid = ::OpenAPI::fromJsonValue(group, json[QString("group")]);
    m_group_isSet = !json[QString("group")].isNull() && m_group_isValid;
}

QString OAISession_userInfo::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISession_userInfo::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (m_group_isSet) {
        obj.insert(QString("group"), ::OpenAPI::toJsonValue(group));
    }
    return obj;
}

QString OAISession_userInfo::getId() const {
    return id;
}
void OAISession_userInfo::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAISession_userInfo::is_id_Set() const{
    return m_id_isSet;
}

bool OAISession_userInfo::is_id_Valid() const{
    return m_id_isValid;
}

QString OAISession_userInfo::getName() const {
    return name;
}
void OAISession_userInfo::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAISession_userInfo::is_name_Set() const{
    return m_name_isSet;
}

bool OAISession_userInfo::is_name_Valid() const{
    return m_name_isValid;
}

QString OAISession_userInfo::getGroup() const {
    return group;
}
void OAISession_userInfo::setGroup(const QString &group) {
    this->group = group;
    this->m_group_isSet = true;
}

bool OAISession_userInfo::is_group_Set() const{
    return m_group_isSet;
}

bool OAISession_userInfo::is_group_Valid() const{
    return m_group_isValid;
}

bool OAISession_userInfo::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_group_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISession_userInfo::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
