/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISession.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISession::OAISession(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISession::OAISession() {
    this->initializeModel();
}

OAISession::~OAISession() {}

void OAISession::initializeModel() {

    m_gid_isSet = false;
    m_gid_isValid = false;

    m_begin_at_isSet = false;
    m_begin_at_isValid = false;

    m_end_at_isSet = false;
    m_end_at_isValid = false;

    m_result_isSet = false;
    m_result_isValid = false;

    m_user_info_isSet = false;
    m_user_info_isValid = false;

    m_test_info_isSet = false;
    m_test_info_isValid = false;
}

void OAISession::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISession::fromJsonObject(QJsonObject json) {

    m_gid_isValid = ::OpenAPI::fromJsonValue(gid, json[QString("gid")]);
    m_gid_isSet = !json[QString("gid")].isNull() && m_gid_isValid;

    m_begin_at_isValid = ::OpenAPI::fromJsonValue(begin_at, json[QString("beginAt")]);
    m_begin_at_isSet = !json[QString("beginAt")].isNull() && m_begin_at_isValid;

    m_end_at_isValid = ::OpenAPI::fromJsonValue(end_at, json[QString("endAt")]);
    m_end_at_isSet = !json[QString("endAt")].isNull() && m_end_at_isValid;

    m_result_isValid = ::OpenAPI::fromJsonValue(result, json[QString("result")]);
    m_result_isSet = !json[QString("result")].isNull() && m_result_isValid;

    m_user_info_isValid = ::OpenAPI::fromJsonValue(user_info, json[QString("userInfo")]);
    m_user_info_isSet = !json[QString("userInfo")].isNull() && m_user_info_isValid;

    m_test_info_isValid = ::OpenAPI::fromJsonValue(test_info, json[QString("testInfo")]);
    m_test_info_isSet = !json[QString("testInfo")].isNull() && m_test_info_isValid;
}

QString OAISession::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISession::asJsonObject() const {
    QJsonObject obj;
    if (m_gid_isSet) {
        obj.insert(QString("gid"), ::OpenAPI::toJsonValue(gid));
    }
    if (m_begin_at_isSet) {
        obj.insert(QString("beginAt"), ::OpenAPI::toJsonValue(begin_at));
    }
    if (m_end_at_isSet) {
        obj.insert(QString("endAt"), ::OpenAPI::toJsonValue(end_at));
    }
    if (m_result_isSet) {
        obj.insert(QString("result"), ::OpenAPI::toJsonValue(result));
    }
    if (user_info.size() > 0) {
        obj.insert(QString("userInfo"), ::OpenAPI::toJsonValue(user_info));
    }
    if (test_info.size() > 0) {
        obj.insert(QString("testInfo"), ::OpenAPI::toJsonValue(test_info));
    }
    return obj;
}

QString OAISession::getGid() const {
    return gid;
}
void OAISession::setGid(const QString &gid) {
    this->gid = gid;
    this->m_gid_isSet = true;
}

bool OAISession::is_gid_Set() const{
    return m_gid_isSet;
}

bool OAISession::is_gid_Valid() const{
    return m_gid_isValid;
}

QString OAISession::getBeginAt() const {
    return begin_at;
}
void OAISession::setBeginAt(const QString &begin_at) {
    this->begin_at = begin_at;
    this->m_begin_at_isSet = true;
}

bool OAISession::is_begin_at_Set() const{
    return m_begin_at_isSet;
}

bool OAISession::is_begin_at_Valid() const{
    return m_begin_at_isValid;
}

QString OAISession::getEndAt() const {
    return end_at;
}
void OAISession::setEndAt(const QString &end_at) {
    this->end_at = end_at;
    this->m_end_at_isSet = true;
}

bool OAISession::is_end_at_Set() const{
    return m_end_at_isSet;
}

bool OAISession::is_end_at_Valid() const{
    return m_end_at_isValid;
}

QString OAISession::getResult() const {
    return result;
}
void OAISession::setResult(const QString &result) {
    this->result = result;
    this->m_result_isSet = true;
}

bool OAISession::is_result_Set() const{
    return m_result_isSet;
}

bool OAISession::is_result_Valid() const{
    return m_result_isValid;
}

QList<QString> OAISession::getUserInfo() const {
    return user_info;
}
void OAISession::setUserInfo(const QList<QString> &user_info) {
    this->user_info = user_info;
    this->m_user_info_isSet = true;
}

bool OAISession::is_user_info_Set() const{
    return m_user_info_isSet;
}

bool OAISession::is_user_info_Valid() const{
    return m_user_info_isValid;
}

QList<QString> OAISession::getTestInfo() const {
    return test_info;
}
void OAISession::setTestInfo(const QList<QString> &test_info) {
    this->test_info = test_info;
    this->m_test_info_isSet = true;
}

bool OAISession::is_test_info_Set() const{
    return m_test_info_isSet;
}

bool OAISession::is_test_info_Valid() const{
    return m_test_info_isValid;
}

bool OAISession::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_gid_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_begin_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_end_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_result_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (user_info.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (test_info.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISession::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_gid_isValid && m_begin_at_isValid && m_end_at_isValid && m_result_isValid && m_user_info_isValid && m_test_info_isValid && true;
}

} // namespace OpenAPI
