/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISession_testInfo_doneQuestionsArray_inner.h
 *
 * 
 */

#ifndef OAISession_testInfo_doneQuestionsArray_inner_H
#define OAISession_testInfo_doneQuestionsArray_inner_H

#include <QJsonObject>

#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISession_testInfo_doneQuestionsArray_inner : public OAIObject {
public:
    OAISession_testInfo_doneQuestionsArray_inner();
    OAISession_testInfo_doneQuestionsArray_inner(QString json);
    ~OAISession_testInfo_doneQuestionsArray_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getBody() const;
    void setBody(const QString &body);
    bool is_body_Set() const;
    bool is_body_Valid() const;

    QList<QString> getDoAnswers() const;
    void setDoAnswers(const QList<QString> &do_answers);
    bool is_do_answers_Set() const;
    bool is_do_answers_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString body;
    bool m_body_isSet;
    bool m_body_isValid;

    QList<QString> do_answers;
    bool m_do_answers_isSet;
    bool m_do_answers_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISession_testInfo_doneQuestionsArray_inner)

#endif // OAISession_testInfo_doneQuestionsArray_inner_H
