/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISession.h
 *
 * 
 */

#ifndef OAISession_H
#define OAISession_H

#include <QJsonObject>

#include "OAISession_testInfo.h"
#include "OAISession_userInfo.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISession : public OAIObject {
public:
    OAISession();
    OAISession(QString json);
    ~OAISession() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getBeginAt() const;
    void setBeginAt(const QString &begin_at);
    bool is_begin_at_Set() const;
    bool is_begin_at_Valid() const;

    QString getEndAt() const;
    void setEndAt(const QString &end_at);
    bool is_end_at_Set() const;
    bool is_end_at_Valid() const;

    QString getResult() const;
    void setResult(const QString &result);
    bool is_result_Set() const;
    bool is_result_Valid() const;

    OAISession_userInfo getUserInfo() const;
    void setUserInfo(const OAISession_userInfo &user_info);
    bool is_user_info_Set() const;
    bool is_user_info_Valid() const;

    OAISession_testInfo getTestInfo() const;
    void setTestInfo(const OAISession_testInfo &test_info);
    bool is_test_info_Set() const;
    bool is_test_info_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString begin_at;
    bool m_begin_at_isSet;
    bool m_begin_at_isValid;

    QString end_at;
    bool m_end_at_isSet;
    bool m_end_at_isValid;

    QString result;
    bool m_result_isSet;
    bool m_result_isValid;

    OAISession_userInfo user_info;
    bool m_user_info_isSet;
    bool m_user_info_isValid;

    OAISession_testInfo test_info;
    bool m_test_info_isSet;
    bool m_test_info_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISession)

#endif // OAISession_H
