/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAISessionUsersApiRequest_H
#define OAI_OAISessionUsersApiRequest_H

#include <QObject>
#include <QStringList>
#include <QMultiMap>
#include <QNetworkReply>
#include <QSharedPointer>

#include <qhttpengine/socket.h>
#include "OAIAnswer.h"
#include "OAIChallengeID.h"
#include "OAIError.h"
#include "OAIQuestion.h"
#include "OAISession.h"
#include <QString>
#include "OAISessionUsersApiHandler.h"

namespace OpenAPI {

class OAISessionUsersApiRequest : public QObject
{
    Q_OBJECT

public:
    OAISessionUsersApiRequest(QHttpEngine::Socket *s, QSharedPointer<OAISessionUsersApiHandler> handler);
    virtual ~OAISessionUsersApiRequest();

    void getQuestionBySessionIDRequest(const QString& session_id);
    void getSessionStateRequest(const QString& session_id);
    void pushAnswerRequest();
    void startTestSessionRequest();
    

    void getQuestionBySessionIDResponse(const OAIQuestion& res);
    void getSessionStateResponse(const OAISession& res);
    void pushAnswerResponse();
    void startTestSessionResponse(const QString& res);
    

    void getQuestionBySessionIDError(const OAIQuestion& res, QNetworkReply::NetworkError error_type, QString& error_str);
    void getSessionStateError(const OAISession& res, QNetworkReply::NetworkError error_type, QString& error_str);
    void pushAnswerError(QNetworkReply::NetworkError error_type, QString& error_str);
    void startTestSessionError(const QString& res, QNetworkReply::NetworkError error_type, QString& error_str);
    

    void sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type);

    void sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type);

    QMap<QString, QString> getRequestHeaders() const;

    QHttpEngine::Socket* getRawSocket();

    void setResponseHeaders(const QMultiMap<QString,QString>& headers);

signals:
    void getQuestionBySessionID(QString session_id);
    void getSessionState(QString session_id);
    void pushAnswer(OAIAnswer oai_answer);
    void startTestSession(OAIChallengeID oai_challenge_id);
    

private:
    QMap<QString, QString> requestHeaders;
    QMap<QString, QString> responseHeaders;
    QHttpEngine::Socket  *socket;
    QSharedPointer<OAISessionUsersApiHandler> handler;

    inline void setSocketResponseHeaders(){
        QHttpEngine::Socket::HeaderMap resHeaders;
        for(auto itr = responseHeaders.begin(); itr != responseHeaders.end(); ++itr) {
            resHeaders.insert(itr.key().toUtf8(), itr.value().toUtf8());
        }
        socket->setHeaders(resHeaders);
    }
};

}

#endif // OAI_OAISessionUsersApiRequest_H
