/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIChallengesAdministratorApiHandler_H
#define OAI_OAIChallengesAdministratorApiHandler_H

#include <QObject>

#include "../models/OAIChallenge.h"
#include "../models/OAIError.h"
#include <QString>

#include "../appEngine/testManager.h"
#include "../appDataORM/appDataManager.h"

namespace OpenAPI {

class OAIChallengesAdministratorApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIChallengesAdministratorApiHandler();
    virtual ~OAIChallengesAdministratorApiHandler();


public slots:
    virtual void addChallenge(OAIChallenge oai_challenge);
    virtual void deleteChallengeById(QString challenge_id);

private:
    TestManager* mTestManager;
    DataManager* mDataManager;
};

}

#endif // OAI_OAIChallengesAdministratorApiHandler_H
