/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIChallengesAdministratorApiHandler.h"
#include "OAIChallengesAdministratorApiRequest.h"

namespace OpenAPI {

OAIChallengesAdministratorApiHandler::OAIChallengesAdministratorApiHandler(){
    // Pattern singletone
    mTestManager = TestManager::getInstance();
    mDataManager = DataManager::getInstance();
}

OAIChallengesAdministratorApiHandler::~OAIChallengesAdministratorApiHandler(){
    delete mTestManager;
    delete mDataManager;
}

void OAIChallengesAdministratorApiHandler::addChallenge(OAIChallenge oai_challenge) {
    auto reqObj = qobject_cast<OAIChallengesAdministratorApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        OAIChallenge res;
        if (mDataManager->addChallengeToFile(oai_challenge.asJsonObject())){
            res = oai_challenge;
        }
        reqObj->addChallengeResponse(res);
    }
}
void OAIChallengesAdministratorApiHandler::deleteChallengeById(QString challenge_gid) {
    auto reqObj = qobject_cast<OAIChallengesAdministratorApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        if (mDataManager->delChallengeFromFile(challenge_gid)){
            reqObj->deleteChallengeByIdResponse();
        }
        else{
            QString error("Challenge delete error!");
            reqObj->deleteChallengeByIdError(QNetworkReply::ContentGoneError, error);
        }
    }
}


}
