/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIChallengesUsersApiHandler_H
#define OAI_OAIChallengesUsersApiHandler_H

#include <QObject>

#include "../models/OAIChallenge.h"
#include "../models/OAIError.h"
#include <QList>
#include <QString>

#include "../appEngine/testManager.h"
#include "../appDataORM/appDataManager.h"

namespace OpenAPI {

class OAIChallengesUsersApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIChallengesUsersApiHandler();
    virtual ~OAIChallengesUsersApiHandler();


public slots:
    virtual void getAllChallenges();
    virtual void getChallengeById(QString challenge_id);

private:
    TestManager* mTestManager;
    DataManager* mDataManager;
};

}

#endif // OAI_OAIChallengesUsersApiHandler_H
