/**
 * Study-Test.Online - сервис проведения тестирования
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAISessionUsersApiHandler.h"
#include "OAISessionUsersApiRequest.h"

// >>>
#include "../appEngine/testManager.h"
// <<<

namespace OpenAPI {

OAISessionUsersApiHandler::OAISessionUsersApiHandler(){
    mTestManager = TestManager::getInstance();
}

OAISessionUsersApiHandler::~OAISessionUsersApiHandler(){
    delete mTestManager;
}

void OAISessionUsersApiHandler::getQuestionBySessionID(QString session_gid) {
    Q_UNUSED(session_gid);
    auto reqObj = qobject_cast<OAISessionUsersApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        OAIQuestion res;
        reqObj->getQuestionBySessionIDResponse(res);
    }
}
void OAISessionUsersApiHandler::getSessionState(QString session_gid) {
    Q_UNUSED(session_gid);
    qDebug() << "Hi session";
    auto reqObj = qobject_cast<OAISessionUsersApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        OAISession res;
        reqObj->getSessionStateResponse(res);
    }
}
void OAISessionUsersApiHandler::pushAnswer(OAIAnswer oai_answer) {
    Q_UNUSED(oai_answer);
    auto reqObj = qobject_cast<OAISessionUsersApiRequest*>(sender());
    if( reqObj != nullptr )
    {

        reqObj->pushAnswerResponse();
    }
}

void OAISessionUsersApiHandler::startTestSession(OAIChallengeID oai_challenge_id) {
    auto reqObj = qobject_cast<OAISessionUsersApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        QJsonObject jsonObj = oai_challenge_id.asJsonObject();
        QString challengeGID = jsonObj["gid"].toString();
        QString res(mTestManager->createSession(challengeGID));
        reqObj->startTestSessionResponse(res);
    }
  }
}
